---

- meta: flush_handlers

- name: Start or restart traefik container
  become: true
  docker_container:
    name: "{{ traefik_container_name }}"
    image: traefik
    state: "{{ traefik_docker_state | default('started') }}"
    restart: "{{ traefik_docker_restart | default(false) | bool }}"
    networks: "{{ traefik_docker_networks }}"
    volumes:
      - "{{ traefik_conf_location }}/traefik.toml:/etc/traefik/traefik.toml"
    ports:
      - "{{ traefik_http_port }}:80"
      - "{{ traefik_http_admin_port }}:8080"
      - "{{ traefik_https_port }}:443"
